In [2]:
#!pip install pybaseball

In [22]:
from pybaseball import pitching_stats
import pandas as pd
import seaborn as sns
import numpy as np

In [21]:
seasonal_pitching = pitching_stats(1980,2020, ind=1)
career_pitching = pitching_stats(1980, 2020, qual=20, ind=0)

In [23]:
seasonal_pitching.head()

,IDfg,Season,Name,Team,Age,W,L,WAR,ERA,G,...,LA,Barrels,Barrel%,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xERA
22,200,1999,Pedro Martinez,BOS,27,23,4,11.6,2.07,31,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
21,815,1997,Roger Clemens,TOR,34,21,7,10.7,2.05,34,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
124,60,2001,Randy Johnson,ARI,37,21,6,10.4,2.49,35,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
175,60,2000,Randy Johnson,ARI,36,19,7,9.6,2.64,35,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
78,642,1998,Kevin Brown,SDP,33,18,7,9.6,2.38,36,...,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN

In [13]:
for col in seasonal_pitching:
    seasonal_pitching = seasonal_pitching.dropna(thresh=4000, axis=1)

In [16]:
pct_null = seasonal_pitching.isnull().sum() / len(seasonal_pitching)
missing_features = pct_null[pct_null > 0.80].index
seasonal_pitching.drop(missing_features, axis=1, inplace=True)

In [24]:
career_pitching.head()

,IDfg,Name,Team,Age,W,L,ERA,WAR,G,GS,...,LA,Barrels,Barrel%,maxEV,HardHit,HardHit%,Events,CStr%,CSW%,xERA
210,815,Roger Clemens,- - -,33,354,184,3.12,133.7,709,707,...,NaN,0.0,NaN,NaN,0.0,NaN,0,0.166,0.277,NaN
233,104,Greg Maddux,- - -,31,355,227,3.16,116.7,744,740,...,NaN,0.0,NaN,NaN,0.0,NaN,0,0.190,0.269,NaN
318,60,Randy Johnson,- - -,34,303,166,3.29,110.5,618,603,...,NaN,0.0,NaN,NaN,0.0,NaN,0,0.175,0.303,NaN
120,200,Pedro Martinez,- - -,27,219,100,2.93,84.4,476,409,...,NaN,0.0,NaN,NaN,0.0,NaN,0,0.185,0.305,NaN
692,837,Mike Mussina,- - -,31,270,153,3.68,81.2,537,536,...,NaN,0.0,NaN,NaN,0.0,NaN,0,0.201,0.281,NaN

In [30]:
x = career_pitching.columns
for i in range(0, len(x)):
    print(x[i])

IDfg
Name
Team
Age
W
L
ERA
WAR
G
GS
CG
ShO
SV
BS
IP
TBF
H
R
ER
HR
BB
IBB
HBP
WP
BK
SO
GB
FB
LD
IFFB
Balls
Strikes
Pitches
RS
IFH
BU
BUH
K/9
BB/9
K/BB
H/9
HR/9
AVG
WHIP
BABIP
LOB%
FIP
GB/FB
LD%
GB%
FB%
IFFB%
HR/FB
IFH%
BUH%
Starting
Start-IP
Relieving
Relief-IP
RAR
Dollars
tERA
xFIP
WPA
-WPA
+WPA
RE24
REW
pLI
inLI
gmLI
exLI
Pulls
WPA/LI
Clutch
FB% 2
FBv
SL%
SLv
CT%
CTv
CB%
CBv
CH%
CHv
SF%
SFv
KN%
KNv
XX%
PO%
wFB
wSL
wCT
wCB
wCH
wSF
wKN
wFB/C
wSL/C
wCT/C
wCB/C
wCH/C
wSF/C
wKN/C
O-Swing%
Z-Swing%
Swing%
O-Contact%
Z-Contact%
Contact%
Zone%
F-Strike%
SwStr%
HLD
SD
MD
ERA-
FIP-
xFIP-
K%
BB%
SIERA
RS/9
E-F
FA% (sc)
FT% (sc)
FC% (sc)
FS% (sc)
FO% (sc)
SI% (sc)
SL% (sc)
CU% (sc)
KC% (sc)
EP% (sc)
CH% (sc)
SC% (sc)
KN% (sc)
UN% (sc)
vFA (sc)
vFT (sc)
vFC (sc)
vFS (sc)
vFO (sc)
vSI (sc)
vSL (sc)
vCU (sc)
vKC (sc)
vEP (sc)
vCH (sc)
vSC (sc)
vKN (sc)
FA-X (sc)
FT-X (sc)
FC-X (sc)
FS-X (sc)
FO-X (sc)
SI-X (sc)
SL-X (sc)
CU-X (sc)
KC-X (sc)
EP-X (sc)
CH-X (sc)
SC-X (sc)
KN-X (sc)
FA-Z (sc)
FT-Z (sc)
FC-Z (sc)
FS-Z (sc)
FO-Z (sc)
SI-Z (sc)
SL-Z (sc)
CU-Z (sc)
KC-Z (sc)
EP-Z (sc)
CH-Z (sc)
SC-Z (sc)
KN-Z (sc)
wFA (sc)
wFT (sc)
wFC (sc)
wFS (sc)
wFO (sc)
wSI (sc)
wSL (sc)
wCU (sc)
wKC (sc)
wEP (sc)
wCH (sc)
wSC (sc)
wKN (sc)
wFA/C (sc)
wFT/C (sc)
wFC/C (sc)
wFS/C (sc)
wFO/C (sc)
wSI/C (sc)
wSL/C (sc)
wCU/C (sc)
wKC/C (sc)
wEP/C (sc)
wCH/C (sc)
wSC/C (sc)
wKN/C (sc)
O-Swing% (sc)
Z-Swing% (sc)
Swing% (sc)
O-Contact% (sc)
Z-Contact% (sc)
Contact% (sc)
Zone% (sc)
Pace
RA9-WAR
BIP-Wins
LOB-Wins
FDP-Wins
Age Rng
K-BB%
Pull%
Cent%
Oppo%
Soft%
Med%
Hard%
kwERA
TTO%
CH% (pi)
CS% (pi)
CU% (pi)
FA% (pi)
FC% (pi)
FS% (pi)
KN% (pi)
SB% (pi)
SI% (pi)
SL% (pi)
XX% (pi)
vCH (pi)
vCS (pi)
vCU (pi)
vFA (pi)
vFC (pi)
vFS (pi)
vKN (pi)
vSB (pi)
vSI (pi)
vSL (pi)
vXX (pi)
CH-X (pi)
CS-X (pi)
CU-X (pi)
FA-X (pi)
FC-X (pi)
FS-X (pi)
KN-X (pi)
SB-X (pi)
SI-X (pi)
SL-X (pi)
XX-X (pi)
CH-Z (pi)
CS-Z (pi)
CU-Z (pi)
FA-Z (pi)
FC-Z (pi)
FS-Z (pi)
KN-Z (pi)
SB-Z (pi)
SI-Z (pi)
SL-Z (pi)
XX-Z (pi)
wCH (pi)
wCS (pi)
wCU (pi)
wFA (pi)
wFC (pi)
wFS (pi)
wKN (pi)
wSB (pi)
wSI (pi)
wSL (pi)
wXX (pi)
wCH/C (pi)
wCS/C (pi)
wCU/C (pi)
wFA/C (pi)
wFC/C (pi)
wFS/C (pi)
wKN/C (pi)
wSB/C (pi)
wSI/C (pi)
wSL/C (pi)
wXX/C (pi)
O-Swing% (pi)
Z-Swing% (pi)
Swing% (pi)
O-Contact% (pi)
Z-Contact% (pi)
Contact% (pi)
Zone% (pi)
Pace (pi)
FRM
K/9+
BB/9+
K/BB+
H/9+
HR/9+
AVG+
WHIP+
BABIP+
LOB%+
K%+
BB%+
LD%+
GB%+
FB%+
HR/FB%+
Pull%+
Cent%+
Oppo%+
Soft%+
Med%+
Hard%+
EV
LA
Barrels
Barrel%
maxEV
HardHit
HardHit%
Events
CStr%
CSW%
xERA

In [31]:
#Making Stat Specific Dataframes
df_career = pd.DataFrame()
df_career['id'] = career_pitching['IDfg']
df_career['g'] = career_pitching['G']
df_career['war'] = career_pitching['WAR']
df_career['era'] = career_pitching['ERA']
df_career['k/9'] = career_pitching['K/9']

In [32]:
df_career.corr()

           id         g       war       era       k/9
id   1.000000 -0.076986 -0.031068 -0.006473 -0.481491
g   -0.076986  1.000000  0.516386 -0.423136  0.161677
war -0.031068  0.516386  1.000000 -0.296832  0.078824
era -0.006473 -0.423136 -0.296832  1.000000 -0.180620
k/9 -0.481491  0.161677  0.078824 -0.180620  1.000000